//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderDocumentAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI", ConfigurationName="TenderDocumentAPI.TenderDocumentAPI_Port")]
    public interface TenderDocumentAPI_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI:DownloadDocument", ReplyAction="*")]
        TenderDocumentAPI.DownloadDocument_Result DownloadDocument(TenderDocumentAPI.DownloadDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI:DownloadDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TenderDocumentAPI.DownloadDocument_Result> DownloadDocumentAsync(TenderDocumentAPI.DownloadDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI:UploadTenderDocument", ReplyAction="*")]
        TenderDocumentAPI.UploadTenderDocument_Result UploadTenderDocument(TenderDocumentAPI.UploadTenderDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI:UploadTenderDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TenderDocumentAPI.UploadTenderDocument_Result> UploadTenderDocumentAsync(TenderDocumentAPI.UploadTenderDocument request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDocument", Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI", Order=0)]
        public TenderDocumentAPI.DownloadDocumentBody Body;
        
        public DownloadDocument()
        {
        }
        
        public DownloadDocument(TenderDocumentAPI.DownloadDocumentBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI")]
    public partial class DownloadDocumentBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentId;
        
        public DownloadDocumentBody()
        {
        }
        
        public DownloadDocumentBody(string documentId)
        {
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocument_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDocument_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI", Order=0)]
        public TenderDocumentAPI.DownloadDocument_ResultBody Body;
        
        public DownloadDocument_Result()
        {
        }
        
        public DownloadDocument_Result(TenderDocumentAPI.DownloadDocument_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI")]
    public partial class DownloadDocument_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public DownloadDocument_ResultBody()
        {
        }
        
        public DownloadDocument_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTenderDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTenderDocument", Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI", Order=0)]
        public TenderDocumentAPI.UploadTenderDocumentBody Body;
        
        public UploadTenderDocument()
        {
        }
        
        public UploadTenderDocument(TenderDocumentAPI.UploadTenderDocumentBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI")]
    public partial class UploadTenderDocumentBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tenderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string securityLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isEncrypted;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string uploadedBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string vendorNo;
        
        public UploadTenderDocumentBody()
        {
        }
        
        public UploadTenderDocumentBody(string tenderId, string fileName, string fileContent, string documentType, string securityLevel, bool isEncrypted, string uploadedBy, string vendorNo)
        {
            this.tenderId = tenderId;
            this.fileName = fileName;
            this.fileContent = fileContent;
            this.documentType = documentType;
            this.securityLevel = securityLevel;
            this.isEncrypted = isEncrypted;
            this.uploadedBy = uploadedBy;
            this.vendorNo = vendorNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTenderDocument_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTenderDocument_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI", Order=0)]
        public TenderDocumentAPI.UploadTenderDocument_ResultBody Body;
        
        public UploadTenderDocument_Result()
        {
        }
        
        public UploadTenderDocument_Result(TenderDocumentAPI.UploadTenderDocument_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TenderDocumentAPI")]
    public partial class UploadTenderDocument_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public UploadTenderDocument_ResultBody()
        {
        }
        
        public UploadTenderDocument_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TenderDocumentAPI_PortChannel : TenderDocumentAPI.TenderDocumentAPI_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TenderDocumentAPI_PortClient : System.ServiceModel.ClientBase<TenderDocumentAPI.TenderDocumentAPI_Port>, TenderDocumentAPI.TenderDocumentAPI_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TenderDocumentAPI_PortClient() : 
                base(TenderDocumentAPI_PortClient.GetDefaultBinding(), TenderDocumentAPI_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TenderDocumentAPI_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TenderDocumentAPI_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(TenderDocumentAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), TenderDocumentAPI_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TenderDocumentAPI_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TenderDocumentAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TenderDocumentAPI_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TenderDocumentAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TenderDocumentAPI_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TenderDocumentAPI.DownloadDocument_Result DownloadDocument(TenderDocumentAPI.DownloadDocument request)
        {
            return base.Channel.DownloadDocument(request);
        }
        
        public System.Threading.Tasks.Task<TenderDocumentAPI.DownloadDocument_Result> DownloadDocumentAsync(TenderDocumentAPI.DownloadDocument request)
        {
            return base.Channel.DownloadDocumentAsync(request);
        }
        
        public TenderDocumentAPI.UploadTenderDocument_Result UploadTenderDocument(TenderDocumentAPI.UploadTenderDocument request)
        {
            return base.Channel.UploadTenderDocument(request);
        }
        
        public System.Threading.Tasks.Task<TenderDocumentAPI.UploadTenderDocument_Result> UploadTenderDocumentAsync(TenderDocumentAPI.UploadTenderDocument request)
        {
            return base.Channel.UploadTenderDocumentAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TenderDocumentAPI_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TenderDocumentAPI_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://bc26-default:7047/BC/WS/CRONUS International Ltd./Codeunit/TenderDocumentA" +
                        "PI?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TenderDocumentAPI_PortClient.GetBindingForEndpoint(EndpointConfiguration.TenderDocumentAPI_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TenderDocumentAPI_PortClient.GetEndpointAddress(EndpointConfiguration.TenderDocumentAPI_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            TenderDocumentAPI_Port,
        }
    }
}
