//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAuthMgmt
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", ConfigurationName="PortalAuthMgmt.PortalAuthManagement_Port")]
    public interface PortalAuthManagement_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:CreateUser", ReplyAction="*")]
        PortalAuthMgmt.CreateUser_Result CreateUser(PortalAuthMgmt.CreateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalAuthMgmt.CreateUser_Result> CreateUserAsync(PortalAuthMgmt.CreateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:GetProfile", ReplyAction="*")]
        PortalAuthMgmt.GetProfile_Result GetProfile(PortalAuthMgmt.GetProfile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:GetProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalAuthMgmt.GetProfile_Result> GetProfileAsync(PortalAuthMgmt.GetProfile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:GetUserPasswordHash", ReplyAction="*")]
        PortalAuthMgmt.GetUserPasswordHash_Result GetUserPasswordHash(PortalAuthMgmt.GetUserPasswordHash request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:GetUserPasswordHash", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalAuthMgmt.GetUserPasswordHash_Result> GetUserPasswordHashAsync(PortalAuthMgmt.GetUserPasswordHash request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:UpdateProfile", ReplyAction="*")]
        PortalAuthMgmt.UpdateProfile_Result UpdateProfile(PortalAuthMgmt.UpdateProfile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalAuthMgmt.UpdateProfile_Result> UpdateProfileAsync(PortalAuthMgmt.UpdateProfile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:ValidateUser", ReplyAction="*")]
        PortalAuthMgmt.ValidateUser_Result ValidateUser(PortalAuthMgmt.ValidateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement:ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalAuthMgmt.ValidateUser_Result> ValidateUserAsync(PortalAuthMgmt.ValidateUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.CreateUserBody Body;
        
        public CreateUser()
        {
        }
        
        public CreateUser(PortalAuthMgmt.CreateUserBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class CreateUserBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fullName;
        
        public CreateUserBody()
        {
        }
        
        public CreateUserBody(string email, string passwordHash, string fullName)
        {
            this.email = email;
            this.passwordHash = passwordHash;
            this.fullName = fullName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUser_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.CreateUser_ResultBody Body;
        
        public CreateUser_Result()
        {
        }
        
        public CreateUser_Result(PortalAuthMgmt.CreateUser_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class CreateUser_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        public CreateUser_ResultBody()
        {
        }
        
        public CreateUser_ResultBody(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfile
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfile", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.GetProfileBody Body;
        
        public GetProfile()
        {
        }
        
        public GetProfile(PortalAuthMgmt.GetProfileBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class GetProfileBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string profilePictureBase64;
        
        public GetProfileBody()
        {
        }
        
        public GetProfileBody(string email, string companyName, string phoneNumber, string profilePictureBase64)
        {
            this.email = email;
            this.companyName = companyName;
            this.phoneNumber = phoneNumber;
            this.profilePictureBase64 = profilePictureBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfile_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfile_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.GetProfile_ResultBody Body;
        
        public GetProfile_Result()
        {
        }
        
        public GetProfile_Result(PortalAuthMgmt.GetProfile_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class GetProfile_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string profilePictureBase64;
        
        public GetProfile_ResultBody()
        {
        }
        
        public GetProfile_ResultBody(bool return_value, string companyName, string phoneNumber, string profilePictureBase64)
        {
            this.return_value = return_value;
            this.companyName = companyName;
            this.phoneNumber = phoneNumber;
            this.profilePictureBase64 = profilePictureBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPasswordHash
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPasswordHash", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.GetUserPasswordHashBody Body;
        
        public GetUserPasswordHash()
        {
        }
        
        public GetUserPasswordHash(PortalAuthMgmt.GetUserPasswordHashBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class GetUserPasswordHashBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetUserPasswordHashBody()
        {
        }
        
        public GetUserPasswordHashBody(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPasswordHash_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPasswordHash_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.GetUserPasswordHash_ResultBody Body;
        
        public GetUserPasswordHash_Result()
        {
        }
        
        public GetUserPasswordHash_Result(PortalAuthMgmt.GetUserPasswordHash_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class GetUserPasswordHash_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public GetUserPasswordHash_ResultBody()
        {
        }
        
        public GetUserPasswordHash_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfile
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfile", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.UpdateProfileBody Body;
        
        public UpdateProfile()
        {
        }
        
        public UpdateProfile(PortalAuthMgmt.UpdateProfileBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class UpdateProfileBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string profilePictureBase64;
        
        public UpdateProfileBody()
        {
        }
        
        public UpdateProfileBody(string email, string companyName, string phoneNumber, string profilePictureBase64)
        {
            this.email = email;
            this.companyName = companyName;
            this.phoneNumber = phoneNumber;
            this.profilePictureBase64 = profilePictureBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfile_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfile_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.UpdateProfile_ResultBody Body;
        
        public UpdateProfile_Result()
        {
        }
        
        public UpdateProfile_Result(PortalAuthMgmt.UpdateProfile_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class UpdateProfile_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        public UpdateProfile_ResultBody()
        {
        }
        
        public UpdateProfile_ResultBody(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.ValidateUserBody Body;
        
        public ValidateUser()
        {
        }
        
        public ValidateUser(PortalAuthMgmt.ValidateUserBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class ValidateUserBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordHash;
        
        public ValidateUserBody()
        {
        }
        
        public ValidateUserBody(string email, string passwordHash)
        {
            this.email = email;
            this.passwordHash = passwordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUser_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement", Order=0)]
        public PortalAuthMgmt.ValidateUser_ResultBody Body;
        
        public ValidateUser_Result()
        {
        }
        
        public ValidateUser_Result(PortalAuthMgmt.ValidateUser_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalAuthManagement")]
    public partial class ValidateUser_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        public ValidateUser_ResultBody()
        {
        }
        
        public ValidateUser_ResultBody(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PortalAuthManagement_PortChannel : PortalAuthMgmt.PortalAuthManagement_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PortalAuthManagement_PortClient : System.ServiceModel.ClientBase<PortalAuthMgmt.PortalAuthManagement_Port>, PortalAuthMgmt.PortalAuthManagement_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PortalAuthManagement_PortClient() : 
                base(PortalAuthManagement_PortClient.GetDefaultBinding(), PortalAuthManagement_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PortalAuthManagement_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalAuthManagement_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(PortalAuthManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), PortalAuthManagement_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalAuthManagement_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PortalAuthManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalAuthManagement_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PortalAuthManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalAuthManagement_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PortalAuthMgmt.CreateUser_Result CreateUser(PortalAuthMgmt.CreateUser request)
        {
            return base.Channel.CreateUser(request);
        }
        
        public System.Threading.Tasks.Task<PortalAuthMgmt.CreateUser_Result> CreateUserAsync(PortalAuthMgmt.CreateUser request)
        {
            return base.Channel.CreateUserAsync(request);
        }
        
        public PortalAuthMgmt.GetProfile_Result GetProfile(PortalAuthMgmt.GetProfile request)
        {
            return base.Channel.GetProfile(request);
        }
        
        public System.Threading.Tasks.Task<PortalAuthMgmt.GetProfile_Result> GetProfileAsync(PortalAuthMgmt.GetProfile request)
        {
            return base.Channel.GetProfileAsync(request);
        }
        
        public PortalAuthMgmt.GetUserPasswordHash_Result GetUserPasswordHash(PortalAuthMgmt.GetUserPasswordHash request)
        {
            return base.Channel.GetUserPasswordHash(request);
        }
        
        public System.Threading.Tasks.Task<PortalAuthMgmt.GetUserPasswordHash_Result> GetUserPasswordHashAsync(PortalAuthMgmt.GetUserPasswordHash request)
        {
            return base.Channel.GetUserPasswordHashAsync(request);
        }
        
        public PortalAuthMgmt.UpdateProfile_Result UpdateProfile(PortalAuthMgmt.UpdateProfile request)
        {
            return base.Channel.UpdateProfile(request);
        }
        
        public System.Threading.Tasks.Task<PortalAuthMgmt.UpdateProfile_Result> UpdateProfileAsync(PortalAuthMgmt.UpdateProfile request)
        {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public PortalAuthMgmt.ValidateUser_Result ValidateUser(PortalAuthMgmt.ValidateUser request)
        {
            return base.Channel.ValidateUser(request);
        }
        
        public System.Threading.Tasks.Task<PortalAuthMgmt.ValidateUser_Result> ValidateUserAsync(PortalAuthMgmt.ValidateUser request)
        {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalAuthManagement_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalAuthManagement_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://bc26-default:7047/BC/WS/CRONUS International Ltd./Codeunit/PortalAuthManag" +
                        "ement?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PortalAuthManagement_PortClient.GetBindingForEndpoint(EndpointConfiguration.PortalAuthManagement_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PortalAuthManagement_PortClient.GetEndpointAddress(EndpointConfiguration.PortalAuthManagement_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            PortalAuthManagement_Port,
        }
    }
}
