//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFQVendorManage
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", ConfigurationName="RFQVendorManage.RFQVendorPortalAPI_Port")]
    public interface RFQVendorPortalAPI_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:GetRFQLines", ReplyAction="*")]
        RFQVendorManage.GetRFQLines_Result GetRFQLines(RFQVendorManage.GetRFQLines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:GetRFQLines", ReplyAction="*")]
        System.Threading.Tasks.Task<RFQVendorManage.GetRFQLines_Result> GetRFQLinesAsync(RFQVendorManage.GetRFQLines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:GetVendorNoByEmail", ReplyAction="*")]
        RFQVendorManage.GetVendorNoByEmail_Result GetVendorNoByEmail(RFQVendorManage.GetVendorNoByEmail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:GetVendorNoByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<RFQVendorManage.GetVendorNoByEmail_Result> GetVendorNoByEmailAsync(RFQVendorManage.GetVendorNoByEmail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:SubmitMultipleQuotes", ReplyAction="*")]
        RFQVendorManage.SubmitMultipleQuotes_Result SubmitMultipleQuotes(RFQVendorManage.SubmitMultipleQuotes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:SubmitMultipleQuotes", ReplyAction="*")]
        System.Threading.Tasks.Task<RFQVendorManage.SubmitMultipleQuotes_Result> SubmitMultipleQuotesAsync(RFQVendorManage.SubmitMultipleQuotes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:SubmitSingleQuote", ReplyAction="*")]
        RFQVendorManage.SubmitSingleQuote_Result SubmitSingleQuote(RFQVendorManage.SubmitSingleQuote request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI:SubmitSingleQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<RFQVendorManage.SubmitSingleQuote_Result> SubmitSingleQuoteAsync(RFQVendorManage.SubmitSingleQuote request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRFQLines
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRFQLines", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.GetRFQLinesBody Body;
        
        public GetRFQLines()
        {
        }
        
        public GetRFQLines(RFQVendorManage.GetRFQLinesBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class GetRFQLinesBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vendorNo;
        
        public GetRFQLinesBody()
        {
        }
        
        public GetRFQLinesBody(string vendorNo)
        {
            this.vendorNo = vendorNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRFQLines_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRFQLines_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.GetRFQLines_ResultBody Body;
        
        public GetRFQLines_Result()
        {
        }
        
        public GetRFQLines_Result(RFQVendorManage.GetRFQLines_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class GetRFQLines_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public GetRFQLines_ResultBody()
        {
        }
        
        public GetRFQLines_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVendorNoByEmail
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVendorNoByEmail", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.GetVendorNoByEmailBody Body;
        
        public GetVendorNoByEmail()
        {
        }
        
        public GetVendorNoByEmail(RFQVendorManage.GetVendorNoByEmailBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class GetVendorNoByEmailBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetVendorNoByEmailBody()
        {
        }
        
        public GetVendorNoByEmailBody(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVendorNoByEmail_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVendorNoByEmail_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.GetVendorNoByEmail_ResultBody Body;
        
        public GetVendorNoByEmail_Result()
        {
        }
        
        public GetVendorNoByEmail_Result(RFQVendorManage.GetVendorNoByEmail_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class GetVendorNoByEmail_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public GetVendorNoByEmail_ResultBody()
        {
        }
        
        public GetVendorNoByEmail_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitMultipleQuotes
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitMultipleQuotes", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.SubmitMultipleQuotesBody Body;
        
        public SubmitMultipleQuotes()
        {
        }
        
        public SubmitMultipleQuotes(RFQVendorManage.SubmitMultipleQuotesBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class SubmitMultipleQuotesBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vendorNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string quotesJson;
        
        public SubmitMultipleQuotesBody()
        {
        }
        
        public SubmitMultipleQuotesBody(string vendorNo, string quotesJson)
        {
            this.vendorNo = vendorNo;
            this.quotesJson = quotesJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitMultipleQuotes_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitMultipleQuotes_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.SubmitMultipleQuotes_ResultBody Body;
        
        public SubmitMultipleQuotes_Result()
        {
        }
        
        public SubmitMultipleQuotes_Result(RFQVendorManage.SubmitMultipleQuotes_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class SubmitMultipleQuotes_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public SubmitMultipleQuotes_ResultBody()
        {
        }
        
        public SubmitMultipleQuotes_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSingleQuote
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSingleQuote", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.SubmitSingleQuoteBody Body;
        
        public SubmitSingleQuote()
        {
        }
        
        public SubmitSingleQuote(RFQVendorManage.SubmitSingleQuoteBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class SubmitSingleQuoteBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vendorNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string itemNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal unitCost;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool priceIncludesVAT;
        
        public SubmitSingleQuoteBody()
        {
        }
        
        public SubmitSingleQuoteBody(string vendorNo, string itemNo, decimal unitCost, bool priceIncludesVAT)
        {
            this.vendorNo = vendorNo;
            this.itemNo = itemNo;
            this.unitCost = unitCost;
            this.priceIncludesVAT = priceIncludesVAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSingleQuote_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSingleQuote_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI", Order=0)]
        public RFQVendorManage.SubmitSingleQuote_ResultBody Body;
        
        public SubmitSingleQuote_Result()
        {
        }
        
        public SubmitSingleQuote_Result(RFQVendorManage.SubmitSingleQuote_ResultBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/RFQVendorPortalAPI")]
    public partial class SubmitSingleQuote_ResultBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        public SubmitSingleQuote_ResultBody()
        {
        }
        
        public SubmitSingleQuote_ResultBody(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface RFQVendorPortalAPI_PortChannel : RFQVendorManage.RFQVendorPortalAPI_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class RFQVendorPortalAPI_PortClient : System.ServiceModel.ClientBase<RFQVendorManage.RFQVendorPortalAPI_Port>, RFQVendorManage.RFQVendorPortalAPI_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RFQVendorPortalAPI_PortClient() : 
                base(RFQVendorPortalAPI_PortClient.GetDefaultBinding(), RFQVendorPortalAPI_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RFQVendorPortalAPI_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RFQVendorPortalAPI_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(RFQVendorPortalAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), RFQVendorPortalAPI_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RFQVendorPortalAPI_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RFQVendorPortalAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RFQVendorPortalAPI_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RFQVendorPortalAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RFQVendorPortalAPI_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public RFQVendorManage.GetRFQLines_Result GetRFQLines(RFQVendorManage.GetRFQLines request)
        {
            return base.Channel.GetRFQLines(request);
        }
        
        public System.Threading.Tasks.Task<RFQVendorManage.GetRFQLines_Result> GetRFQLinesAsync(RFQVendorManage.GetRFQLines request)
        {
            return base.Channel.GetRFQLinesAsync(request);
        }
        
        public RFQVendorManage.GetVendorNoByEmail_Result GetVendorNoByEmail(RFQVendorManage.GetVendorNoByEmail request)
        {
            return base.Channel.GetVendorNoByEmail(request);
        }
        
        public System.Threading.Tasks.Task<RFQVendorManage.GetVendorNoByEmail_Result> GetVendorNoByEmailAsync(RFQVendorManage.GetVendorNoByEmail request)
        {
            return base.Channel.GetVendorNoByEmailAsync(request);
        }
        
        public RFQVendorManage.SubmitMultipleQuotes_Result SubmitMultipleQuotes(RFQVendorManage.SubmitMultipleQuotes request)
        {
            return base.Channel.SubmitMultipleQuotes(request);
        }
        
        public System.Threading.Tasks.Task<RFQVendorManage.SubmitMultipleQuotes_Result> SubmitMultipleQuotesAsync(RFQVendorManage.SubmitMultipleQuotes request)
        {
            return base.Channel.SubmitMultipleQuotesAsync(request);
        }
        
        public RFQVendorManage.SubmitSingleQuote_Result SubmitSingleQuote(RFQVendorManage.SubmitSingleQuote request)
        {
            return base.Channel.SubmitSingleQuote(request);
        }
        
        public System.Threading.Tasks.Task<RFQVendorManage.SubmitSingleQuote_Result> SubmitSingleQuoteAsync(RFQVendorManage.SubmitSingleQuote request)
        {
            return base.Channel.SubmitSingleQuoteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RFQVendorPortalAPI_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RFQVendorPortalAPI_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://bc26-default:7047/BC/WS/CRONUS International Ltd./Codeunit/RFQVendorPortal" +
                        "API?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RFQVendorPortalAPI_PortClient.GetBindingForEndpoint(EndpointConfiguration.RFQVendorPortalAPI_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RFQVendorPortalAPI_PortClient.GetEndpointAddress(EndpointConfiguration.RFQVendorPortalAPI_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            RFQVendorPortalAPI_Port,
        }
    }
}
